<?php

$doctorOnly = 'Chi dung khi co chi dinh cua bac si/duoc si.';
$prescription = 'Thuoc ke don hoac can duoc tu van chuyen mon, khong tu y dung.';

return [
    'items' => [
        ['TenThuoc' => 'Paracetamol', 'HoatChat' => 'Paracetamol', 'NhomThuoc' => 'Giam dau, ha sot', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => 'Goi y nhap lich theo huong dan tren bao bi hoac tu van duoc si.', 'CanhBao' => 'Can than voi benh gan, ruou bia va dung trung nhieu thuoc co paracetamol.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Panadol', 'HoatChat' => 'Paracetamol', 'NhomThuoc' => 'Giam dau, ha sot', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => 'Thuong gap tai nha thuoc Viet Nam.', 'CanhBao' => 'Kiem tra thanh phan de tranh trung paracetamol.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Hapacol', 'HoatChat' => 'Paracetamol', 'NhomThuoc' => 'Giam dau, ha sot', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '650', 'GhiChu' => 'Nhap ham luong dung voi san pham dang co.', 'CanhBao' => 'Khong tu tang tong lieu trong ngay.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Efferalgan', 'HoatChat' => 'Paracetamol', 'NhomThuoc' => 'Giam dau, ha sot', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => 'Dang vien sui/ vien nen tuy san pham.', 'CanhBao' => 'Can than voi ham luong natri neu la vien sui va nguoi can han che muoi.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Ibuprofen', 'HoatChat' => 'Ibuprofen', 'NhomThuoc' => 'Giam dau, khang viem', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '200', 'GhiChu' => $doctorOnly, 'CanhBao' => 'Can than voi dau da day, benh than, dang dung thuoc chong dong.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Aspirin', 'HoatChat' => 'Acetylsalicylic acid', 'NhomThuoc' => 'Giam dau, khang viem', 'IconThuoc' => 'pill', 'DonVi' => 'mg', 'LieuLuong' => '81', 'GhiChu' => $prescription, 'CanhBao' => 'Can than nguy co chay mau, dau da day; khong tu dung dai han.', 'NguonThamKhao' => 'Danh muc nha thuoc'],

        ['TenThuoc' => 'Vitamin C', 'HoatChat' => 'Ascorbic acid', 'NhomThuoc' => 'Vitamin va khoang chat', 'IconThuoc' => 'vitamin', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => 'Thuong dung bo sung vitamin.', 'CanhBao' => 'Nguoi co tien su soi than/benh than nen hoi y kien chuyen mon.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Vitamin D3', 'HoatChat' => 'Cholecalciferol', 'NhomThuoc' => 'Vitamin va khoang chat', 'IconThuoc' => 'vitamin', 'DonVi' => 'IU', 'LieuLuong' => '1000', 'GhiChu' => 'Nhap ham luong dung voi san pham dang su dung.', 'CanhBao' => 'Khong tu dung lieu cao keo dai.', 'NguonThamKhao' => 'Long Chau'],
        ['TenThuoc' => 'Calcium', 'HoatChat' => 'Calcium', 'NhomThuoc' => 'Vitamin va khoang chat', 'IconThuoc' => 'vitamin', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => 'Thuong gap trong nhom bo sung khoang chat.', 'CanhBao' => 'Can than neu soi than hoac dang dung mot so thuoc tim mach.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Magnesium B6', 'HoatChat' => 'Magnesium, Vitamin B6', 'NhomThuoc' => 'Vitamin va khoang chat', 'IconThuoc' => 'vitamin', 'DonVi' => 'vien', 'LieuLuong' => '1', 'GhiChu' => 'Nhap so vien theo huong dan san pham.', 'CanhBao' => 'Nguoi suy than can hoi y kien chuyen mon.', 'NguonThamKhao' => 'Long Chau'],

        ['TenThuoc' => 'Amoxicillin', 'HoatChat' => 'Amoxicillin', 'NhomThuoc' => 'Khang sinh', 'IconThuoc' => 'shield', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => $prescription, 'CanhBao' => 'Khang sinh phai dung theo don; canh bao di ung penicillin.', 'NguonThamKhao' => 'Long Chau, Pharmacity'],
        ['TenThuoc' => 'Augmentin', 'HoatChat' => 'Amoxicillin, Clavulanic acid', 'NhomThuoc' => 'Khang sinh', 'IconThuoc' => 'shield', 'DonVi' => 'mg', 'LieuLuong' => '625', 'GhiChu' => $prescription, 'CanhBao' => 'Can than di ung beta-lactam va tien su van de gan khi dung amoxicillin/clavulanate.', 'NguonThamKhao' => 'Pharmacity'],
        ['TenThuoc' => 'Klamentin', 'HoatChat' => 'Amoxicillin, Clavulanic acid', 'NhomThuoc' => 'Khang sinh', 'IconThuoc' => 'shield', 'DonVi' => 'mg', 'LieuLuong' => '625', 'GhiChu' => $prescription, 'CanhBao' => 'Dung theo don va dung du lieu trinh.', 'NguonThamKhao' => 'Pharmacity'],
        ['TenThuoc' => 'Cephalexin', 'HoatChat' => 'Cephalexin', 'NhomThuoc' => 'Khang sinh', 'IconThuoc' => 'shield', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => $prescription, 'CanhBao' => 'Canh bao di ung cephalosporin/penicillin.', 'NguonThamKhao' => 'Pharmacity'],
        ['TenThuoc' => 'Azithromycin', 'HoatChat' => 'Azithromycin', 'NhomThuoc' => 'Khang sinh', 'IconThuoc' => 'shield', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => $prescription, 'CanhBao' => 'Can than voi benh tim mach, tuong tac thuoc.', 'NguonThamKhao' => 'Danh muc nha thuoc'],

        ['TenThuoc' => 'Cetirizine', 'HoatChat' => 'Cetirizine', 'NhomThuoc' => 'Di ung', 'IconThuoc' => 'allergy', 'DonVi' => 'mg', 'LieuLuong' => '10', 'GhiChu' => 'Goi y cho nhom khang histamin.', 'CanhBao' => 'Co the gay buon ngu o mot so nguoi.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Loratadine', 'HoatChat' => 'Loratadine', 'NhomThuoc' => 'Di ung', 'IconThuoc' => 'allergy', 'DonVi' => 'mg', 'LieuLuong' => '10', 'GhiChu' => 'Goi y cho nhom khang histamin.', 'CanhBao' => 'Nguoi benh gan nen hoi y kien chuyen mon.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Chlorpheniramine', 'HoatChat' => 'Chlorpheniramine', 'NhomThuoc' => 'Di ung', 'IconThuoc' => 'allergy', 'DonVi' => 'mg', 'LieuLuong' => '4', 'GhiChu' => 'Thuong co trong thuoc cam/di ung.', 'CanhBao' => 'De gay buon ngu; can than khi lai xe/van hanh may.', 'NguonThamKhao' => 'Danh muc nha thuoc'],

        ['TenThuoc' => 'Omeprazole', 'HoatChat' => 'Omeprazole', 'NhomThuoc' => 'Da day', 'IconThuoc' => 'stomach', 'DonVi' => 'mg', 'LieuLuong' => '20', 'GhiChu' => $doctorOnly, 'CanhBao' => 'Khong nen tu dung keo dai neu chua duoc danh gia nguyen nhan.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Esomeprazole', 'HoatChat' => 'Esomeprazole', 'NhomThuoc' => 'Da day', 'IconThuoc' => 'stomach', 'DonVi' => 'mg', 'LieuLuong' => '20', 'GhiChu' => $doctorOnly, 'CanhBao' => 'Can than tuong tac va dung keo dai.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Oresol', 'HoatChat' => 'Oral rehydration salts', 'NhomThuoc' => 'Tieu hoa', 'IconThuoc' => 'drop', 'DonVi' => 'goi', 'LieuLuong' => '1', 'GhiChu' => 'Pha dung luong nuoc ghi tren goi.', 'CanhBao' => 'Pha sai nong do co the nguy hiem, tre em can theo doi sat.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Loperamide', 'HoatChat' => 'Loperamide', 'NhomThuoc' => 'Tieu hoa', 'IconThuoc' => 'stomach', 'DonVi' => 'mg', 'LieuLuong' => '2', 'GhiChu' => $doctorOnly, 'CanhBao' => 'Khong tu dung khi tieu chay co sot, co mau, nghi nhiem trung.', 'NguonThamKhao' => 'Danh muc nha thuoc'],

        ['TenThuoc' => 'Amlodipine', 'HoatChat' => 'Amlodipine', 'NhomThuoc' => 'Huyet ap, tim mach', 'IconThuoc' => 'heart', 'DonVi' => 'mg', 'LieuLuong' => '5', 'GhiChu' => $prescription, 'CanhBao' => 'Dung theo don, theo doi huyet ap va phu chan neu co.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Losartan', 'HoatChat' => 'Losartan', 'NhomThuoc' => 'Huyet ap, tim mach', 'IconThuoc' => 'heart', 'DonVi' => 'mg', 'LieuLuong' => '50', 'GhiChu' => $prescription, 'CanhBao' => 'Can theo doi huyet ap, kali mau, chuc nang than theo chi dinh.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Metformin', 'HoatChat' => 'Metformin', 'NhomThuoc' => 'Tieu duong', 'IconThuoc' => 'drop', 'DonVi' => 'mg', 'LieuLuong' => '500', 'GhiChu' => $prescription, 'CanhBao' => 'Dung theo don; can than voi suy than va roi loan tieu hoa.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Gliclazide', 'HoatChat' => 'Gliclazide', 'NhomThuoc' => 'Tieu duong', 'IconThuoc' => 'drop', 'DonVi' => 'mg', 'LieuLuong' => '30', 'GhiChu' => $prescription, 'CanhBao' => 'Co nguy co ha duong huyet, can theo don bac si.', 'NguonThamKhao' => 'Danh muc nha thuoc'],

        ['TenThuoc' => 'Salbutamol', 'HoatChat' => 'Salbutamol', 'NhomThuoc' => 'Ho hap', 'IconThuoc' => 'breath', 'DonVi' => 'mcg', 'LieuLuong' => '100', 'GhiChu' => $prescription, 'CanhBao' => 'Kho tho, kho khe nang can di kham/cap cuu; khong le thuoc cat con.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Acetylcysteine', 'HoatChat' => 'Acetylcysteine', 'NhomThuoc' => 'Ho hap', 'IconThuoc' => 'breath', 'DonVi' => 'mg', 'LieuLuong' => '200', 'GhiChu' => $doctorOnly, 'CanhBao' => 'Nguoi hen phe quan can than khi dung.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
        ['TenThuoc' => 'Povidone iodine', 'HoatChat' => 'Povidone iodine', 'NhomThuoc' => 'Sat trung', 'IconThuoc' => 'firstaid', 'DonVi' => '%', 'LieuLuong' => '10', 'GhiChu' => 'Dung ngoai da theo huong dan san pham.', 'CanhBao' => 'Khong uong, can than voi di ung iod hoac benh ly tuyen giap.', 'NguonThamKhao' => 'Danh muc nha thuoc'],
    ],
];
